# Generated by Django 3.1.2 on 2020-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
