# Generated by Django 3.1.4 on 2021-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmpFlag',
            field=models.CharField(default='20', max_length=2),
        ),
    ]
