# Generated by Django 3.1.2 on 2020-10-27 13:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainPoint', models.IntegerField(null=True)),
                ('totExchangeLike', models.IntegerField(null=True)),
                ('totExchangePoint', models.IntegerField(null=True)),
                ('totSpendPoint', models.IntegerField(null=True)),
                ('lastExchangeDate', models.CharField(max_length=8, null=True)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 22, 36, 13, 836562), null=True)),
                ('insUs', models.CharField(default='defaultValue', max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 22, 36, 13, 836601), null=True)),
                ('modUs', models.CharField(default='defaultValue', max_length=30, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
