# Generated by Django 3.1.4 on 2021-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210307_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tmpFlag',
            field=models.CharField(default='2', max_length=2),
        ),
    ]
