# Generated by Django 3.1.4 on 2021-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210308_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tmpFlag',
            field=models.CharField(default='2', max_length=3),
        ),
    ]
