# Generated by Django 3.1.2 on 2020-11-07 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201105_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='testField',
            new_name='profileName',
        ),
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 19, 24, 526154)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 19, 24, 526194)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 19, 24, 525493), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 19, 24, 525537), null=True),
        ),
    ]
