# Generated by Django 3.1.3 on 2020-11-12 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201110_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 32, 37, 587833)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 32, 37, 587868)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 32, 37, 587159), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 32, 37, 587200), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(upload_to='image'),
        ),
    ]
