# Generated by Django 3.1.3 on 2020-11-15 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20201115_2135'),
        ('users', '0013_auto_20201112_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('bizNo', models.CharField(blank=True, max_length=15)),
                ('bizName', models.CharField(blank=True, max_length=100)),
                ('openDttm', models.CharField(blank=True, max_length=8)),
                ('registerNo', models.CharField(blank=True, max_length=15)),
                ('bizAddr', models.CharField(blank=True, max_length=100)),
                ('storeAddr', models.CharField(blank=True, max_length=100)),
                ('orderYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 817370))),
                ('insUs', models.CharField(null=True, max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 817402))),
                ('modUs', models.CharField(null=True, max_length=30)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageTest',
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 816667)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 816700)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 816018), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 21, 35, 16, 816063), null=True),
        ),
    ]
