# Generated by Django 3.1.3 on 2020-11-18 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201117_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 408023)),
        ),
        migrations.AlterField(
            model_name='business',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 408060)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 407290)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 407324)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 406614), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 406655), null=True),
        ),
    ]
