# Generated by Django 3.1.3 on 2020-11-18 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201118_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 343529)),
        ),
        migrations.AlterField(
            model_name='business',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 343600)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 341544)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 341610)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 340420), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 340494), null=True),
        ),
    ]
