# Generated by Django 3.1.3 on 2020-11-21 05:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201121_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 911323)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 911356)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 910561)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 910595)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 909890), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 909936), null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionDate', models.CharField(blank=True, max_length=8, null=True)),
                ('seq', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='images/question')),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 912133))),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 12, 7, 912168))),
                ('modUs', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
