# Generated by Django 3.1.3 on 2020-11-21 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201121_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='insDt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='insUs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modDt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modUs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionDate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 28130)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 28164)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 27314)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 27345)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 26572), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 23, 46, 26705), null=True),
        ),
    ]
