# Generated by Django 3.1.3 on 2020-11-21 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201121_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 890839)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 890876)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 890012)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 890049)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 889177), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 17, 23, 25, 889328), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
    ]
