# Generated by Django 3.1.3 on 2020-11-21 09:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201121_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 736051)),
        ),
        migrations.AddField(
            model_name='question',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 736086)),
        ),
        migrations.AddField(
            model_name='question',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionDate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 735236)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 735271)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 734459)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 734492)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 733810), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 25, 6, 733854), null=True),
        ),
    ]
