# Generated by Django 3.1.3 on 2020-11-21 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20201121_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='question',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
        migrations.AddField(
            model_name='question',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
        migrations.AddField(
            model_name='question',
            name='img4',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
        migrations.AddField(
            model_name='question',
            name='img5',
            field=models.ImageField(null=True, upload_to='images/question'),
        ),
        migrations.AlterField(
            model_name='business',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 221399)),
        ),
        migrations.AlterField(
            model_name='business',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 221432)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 220672)),
        ),
        migrations.AlterField(
            model_name='myplace',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 220705)),
        ),
        migrations.AlterField(
            model_name='point',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 220007), null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 220057), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 222229)),
        ),
        migrations.AlterField(
            model_name='question',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 20, 3, 23, 222264)),
        ),
    ]
