# Generated by Django 3.1.4 on 2020-12-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201214_1904'),
        ('users', '0032_auto_20201212_1727'),
    ]

    operations = [
    ]
