# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20201225_1359'),
        ('users', '0043_auto_20201225_1053'),
    ]

    operations = [
    ]
