# Generated by Django 3.1.4 on 2020-12-28 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cprt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprtCd', models.CharField(default='000', max_length=5)),
                ('cprtName', models.CharField(default='', max_length=50)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modUs', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprtGroupCd', models.CharField(default='000', max_length=5)),
                ('cprtGroupName', models.CharField(default='', max_length=50)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modUs', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modUs', models.CharField(max_length=30, null=True)),
                ('cprtCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cprts.cprt')),
                ('cprtGroupCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cprts.group')),
            ],
        ),
    ]
