# Generated by Django 3.1.1 on 2020-09-30 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_auto_20200930_1337'),
        ('cprts', '0002_auto_20200930_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprtGroupCd', models.CharField(default='000', max_length=5)),
                ('cprtGrupName', models.CharField(default='', max_length=50)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 37, 37, 30854))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 37, 37, 30886))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprtCd', models.CharField(default='000', max_length=5)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('cprtName', models.CharField(max_length=50)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 37, 37, 30231))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 37, 37, 30266))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Cprt',
        ),
    ]
