# Generated by Django 3.1.1 on 2020-09-30 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_auto_20200930_1703'),
        ('cprts', '0006_auto_20200930_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 518932))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 518970))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='cprtGrupName',
            new_name='cprtGroupName',
        ),
        migrations.RemoveField(
            model_name='cprt',
            name='cprtGroupCd',
        ),
        migrations.AddField(
            model_name='cprt',
            name='cprtName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cprt',
            name='useYn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='cprt',
            name='cprtCd',
            field=models.CharField(default='000', max_length=5),
        ),
        migrations.AlterField(
            model_name='cprt',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 517703)),
        ),
        migrations.AlterField(
            model_name='cprt',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 517741)),
        ),
        migrations.AlterField(
            model_name='group',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 518309)),
        ),
        migrations.AlterField(
            model_name='group',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 3, 48, 518349)),
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.AddField(
            model_name='relation',
            name='cprtCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cprts.cprt'),
        ),
        migrations.AddField(
            model_name='relation',
            name='cprtGroupCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cprts.group'),
        ),
        migrations.AddField(
            model_name='relation',
            name='storeCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
