# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cprts', '0024_auto_20201225_1053'),
        ('cprts', '0025_auto_20201225_1401'),
    ]

    operations = [
    ]
