# Generated by Django 3.1.2 on 2020-10-21 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_auto_20201021_2300'),
        ('keymaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(default='00000', max_length=10)),
                ('storeName', models.CharField(default='', max_length=50)),
                ('storeCeo', models.CharField(max_length=50, null=True)),
                ('bizopNo', models.CharField(max_length=20, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('postCd', models.CharField(max_length=6, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('addr1', models.CharField(max_length=200, null=True)),
                ('addr2', models.CharField(max_length=200, null=True)),
                ('oldAddr', models.CharField(max_length=200, null=True)),
                ('openTm', models.CharField(max_length=6, null=True)),
                ('closeTm', models.CharField(max_length=6, null=True)),
                ('dvYn', models.CharField(default='N', max_length=1)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('bankCd', models.CharField(max_length=3, null=True)),
                ('bankNo', models.CharField(max_length=40, null=True)),
                ('openDt', models.CharField(max_length=8, null=True)),
                ('closeDt', models.CharField(max_length=8, null=True)),
                ('imgLogoUrl', models.CharField(max_length=200, null=True)),
                ('orgIf', models.CharField(max_length=1000, null=True)),
                ('xPosition', models.FloatField(null=True)),
                ('yPosition', models.FloatField(null=True)),
                ('likeCount', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=50, null=True)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 363509))),
                ('insUs', models.CharField( max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 363549))),
                ('modUs', models.CharField( max_length=30)),
                ('brandCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordStartNo', models.CharField(max_length=10, null=True)),
                ('ordEndNo', models.CharField(max_length=10, null=True)),
                ('cntPayYn', models.CharField(max_length=1, null=True)),
                ('kktAlrTmplCd', models.CharField(max_length=50, null=True)),
                ('takeOutYn', models.CharField(default='Y', max_length=1)),
                ('callNoYn', models.CharField(default='Y', max_length=1)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('keymapCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.storekeymap')),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Funset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmnId', models.CharField(max_length=20, null=True)),
                ('normVanCd', models.CharField(max_length=3, null=True)),
                ('callFg', models.CharField(max_length=1, null=True)),
                ('ordPrtTy', models.CharField(max_length=1, null=True)),
                ('alrYn', models.CharField(default='N', max_length=1)),
                ('alrTy', models.CharField(max_length=1, null=True)),
                ('alrPntFg', models.CharField(max_length=1, null=True)),
                ('alrUrl', models.CharField(max_length=100, null=True)),
                ('kktAlrCallId', models.CharField(max_length=20, null=True)),
                ('kktAlrAccessKey', models.CharField(max_length=255, null=True)),
                ('kktAlrFailFg', models.CharField(max_length=1, null=True)),
                ('kktAlrId', models.CharField(max_length=50, null=True)),
                ('kktAlrPw', models.CharField(max_length=50, null=True)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 364498), null=True)),
                ('insUs', models.CharField( max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 364533), null=True)),
                ('modUs', models.CharField( max_length=30, null=True)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
