# Generated by Django 3.1.4 on 2020-12-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20201230_1504'),
        ('stores', '0002_auto_20201230_1454'),
    ]

    operations = [
    ]
