# Generated by Django 3.1.1 on 2020-09-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20200929_2359'),
        ('stores', '0002_remove_store_storename'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bizopNo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='brandCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AddField(
            model_name='store',
            name='postCd',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='store',
            name='storeAddr1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='storeAddr2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='storeCd',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='storeCeo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='storeFax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='storeMail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='storeMobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='storeName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='storeOldAddr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='storeTel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
