# Generated by Django 3.1.4 on 2021-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210308_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='alrYn',
            field=models.CharField(default='N', max_length=17),
        ),
        migrations.AlterField(
            model_name='pos',
            name='callNoYn',
            field=models.CharField(default='Y', max_length=17),
        ),
        migrations.AlterField(
            model_name='pos',
            name='takeOutYn',
            field=models.CharField(default='Y', max_length=17),
        ),
        migrations.AlterField(
            model_name='pos',
            name='useYn',
            field=models.CharField(default='Y', max_length=17),
        ),
        migrations.AlterField(
            model_name='store',
            name='dvYn',
            field=models.CharField(blank=True, default='N', max_length=17),
        ),
        migrations.AlterField(
            model_name='store',
            name='openYn',
            field=models.CharField(default='Y', max_length=17),
        ),
        migrations.AlterField(
            model_name='store',
            name='useYn',
            field=models.CharField(blank=True, default='Y', max_length=17),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='dicType',
            field=models.CharField(default='1', max_length=17),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='likeYn',
            field=models.CharField(default='Y', max_length=17),
        ),
    ]
