# Generated by Django 3.1.1 on 2020-09-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20200929_2359'),
        ('stores', '0003_auto_20200929_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='brandCd',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
    ]
