# Generated by Django 3.1.1 on 2020-09-29 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200929_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bankCd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='store',
            name='bankNo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='store',
            name='closeDt',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='store',
            name='closeTm',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='dvYn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='store',
            name='imgLogoUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 10, 30, 288834)),
        ),
        migrations.AddField(
            model_name='store',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 10, 30, 288878)),
        ),
        migrations.AddField(
            model_name='store',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='openDt',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='store',
            name='openTm',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='store',
            name='orgIf',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='store',
            name='useYn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='store',
            name='xPosition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='yPosition',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
