# Generated by Django 3.1.4 on 2021-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210308_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='alrPntFg',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='alrTy',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='callFg',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrFailFg',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='ordPrtTy',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='dicType',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
