# Generated by Django 3.1.1 on 2020-09-29 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200930_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 21, 13, 409224)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 21, 13, 409262)),
        ),
        migrations.CreateModel(
            name='storeFunset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmnId', models.CharField(blank=True, max_length=20)),
                ('normVanCd', models.CharField(default='000', max_length=3)),
                ('callFg', models.CharField(default='0', max_length=1)),
                ('ordPrtTy', models.CharField(default='0', max_length=1)),
                ('alrYn', models.CharField(default='N', max_length=1)),
                ('alrTy', models.CharField(default='0', max_length=1)),
                ('alrPntFg', models.CharField(default='0', max_length=1)),
                ('alrUrl', models.CharField(blank=True, max_length=100)),
                ('kktAlrCallId', models.CharField(blank=True, max_length=20)),
                ('kktAlrAccessKey', models.CharField(blank=True, max_length=255)),
                ('kktAlrFailFg', models.CharField(default='0', max_length=1)),
                ('kktAlrId', models.CharField(blank=True, max_length=50)),
                ('kktAlrPw', models.CharField(blank=True, max_length=50)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 21, 13, 410368))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 21, 13, 410404))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
