# Generated by Django 3.1.2 on 2020-10-27 14:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0005_auto_20201027_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 33, 23, 330301), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 33, 23, 330342), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 33, 23, 328347)),
        ),
        migrations.RemoveField(
            model_name='store',
            name='likeUser',
        ),
        migrations.AddField(
            model_name='store',
            name='likeUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 33, 23, 328383)),
        ),
    ]
