# Generated by Django 3.1.2 on 2020-10-30 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0012_auto_20201029_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 400355), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 400391), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 398723)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 398761)),
        ),
        migrations.CreateModel(
            name='StoreDic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicType', models.CharField(default='1', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 401665), null=True)),
                ('insUs', models.CharField(default='defaultValue', max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 36, 6, 401702), null=True)),
                ('modUs', models.CharField(default='defaultValue', max_length=30, null=True)),
                ('store', models.ManyToManyField(to='stores.Store')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
