# Generated by Django 3.1.1 on 2020-09-29 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_auto_20200930_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 28, 53, 423279)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 28, 53, 423323)),
        ),
        migrations.AlterField(
            model_name='storefunset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 28, 53, 424372)),
        ),
        migrations.AlterField(
            model_name='storefunset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 28, 53, 424410)),
        ),
    ]
