# Generated by Django 3.1.3 on 2020-11-20 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_auto_20201118_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 914277), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 914312), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='addr1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='addr2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bankCd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bankNo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bizopNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='closeDt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='closeTm',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='dvYn',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='imgLogoUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 2, 35, 11, 913250), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 2, 35, 11, 913302), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='oldAddr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='openDt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='openTm',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='orgIf',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='postCd',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeCeo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='useYn',
            field=models.CharField(blank=True, default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 915610), null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 915646), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 916188), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 35, 11, 916224), null=True),
        ),
    ]
