# Generated by Django 3.1.3 on 2020-11-22 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_auto_20201122_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 39, 3193), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 39, 3233), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 23, 19, 39, 1976), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 23, 19, 39, 2028), null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 39, 5036), null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 39, 5082), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 23, 19, 39, 5724), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='insUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 23, 19, 39, 5766), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='modUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
