# Generated by Django 3.1.2 on 2020-10-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_auto_20201002_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 2, 0, 44, 82458)),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 2, 0, 44, 82497)),
        ),
        migrations.AlterField(
            model_name='store',
            name='addr1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='addr2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bankCd',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bankNo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bizopNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='closeDt',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='closeTm',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='fax',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='imgLogoUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 2, 0, 44, 81211)),
        ),
        migrations.AlterField(
            model_name='store',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 2, 0, 44, 81249)),
        ),
        migrations.AlterField(
            model_name='store',
            name='oldAddr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='openDt',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='openTm',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='orgIf',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='postCd',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeCeo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='xPosition',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='yPosition',
            field=models.FloatField(null=True),
        ),
    ]
