# Generated by Django 3.1.2 on 2020-10-04 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_auto_20201004_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='alrUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 26, 30, 255093)),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrAccessKey',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrCallId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrPw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 26, 30, 255132)),
        ),
        migrations.AlterField(
            model_name='funset',
            name='tmnId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 26, 30, 253858)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 26, 30, 253903)),
        ),
    ]
