# Generated by Django 3.1.4 on 2020-12-23 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0040_auto_20201218_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 23, 42, 40, 382107), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 23, 42, 40, 382159), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 42, 40, 380701), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 42, 40, 380746), null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 23, 42, 40, 383681), null=True),
        ),
        migrations.AlterField(
            model_name='storedic',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 23, 42, 40, 383719), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 42, 40, 384412), null=True),
        ),
        migrations.AlterField(
            model_name='storelike',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 23, 42, 40, 384455), null=True),
        ),
    ]
