# Generated by Django 3.1.2 on 2020-10-04 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0042_auto_20201004_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 29, 13, 602796)),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 29, 13, 602830)),
        ),
        migrations.AlterField(
            model_name='funset',
            name='ordPrtTy',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 29, 13, 601612)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 14, 29, 13, 601656)),
        ),
    ]
