# Generated by Django 3.1.2 on 2020-10-05 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0045_auto_20201004_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 26, 42, 288161), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 26, 42, 288197), null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='kktAlrTmplCd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='ordEndNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='ordStartNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 26, 42, 286919)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 26, 42, 286956)),
        ),
    ]
