# Generated by Django 3.1.2 on 2020-10-05 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0046_auto_20201005_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 27, 15, 124836), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 27, 15, 124872), null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='cntPayYn',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 27, 15, 123500)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 27, 15, 123596)),
        ),
    ]
