# Generated by Django 3.1.2 on 2020-10-10 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0048_auto_20201005_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 39, 0, 247339), null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='kktAlrFailFg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 39, 0, 247373), null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 39, 0, 246239)),
        ),
        migrations.AlterField(
            model_name='store',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 39, 0, 246283)),
        ),
    ]
