# Generated by Django 3.1.2 on 2020-10-21 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_auto_20201021_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festivalCd', models.CharField(default='0000', max_length=5)),
                ('festivalName', models.CharField(default='', max_length=100)),
                ('startDt', models.CharField(default='', max_length=8)),
                ('endDt', models.CharField(default='', max_length=8)),
                ('descriptionHeader', models.CharField(default='', max_length=100)),
                ('descriptionDetail', models.CharField(default='', max_length=500)),
                ('joinCount', models.IntegerField(default=0)),
                ('simulOperCount', models.IntegerField(default=0)),
                ('imgUrl', models.CharField(blank=True, max_length=200)),
                ('innerMapUrl', models.CharField(blank=True, max_length=200)),
                ('addr1', models.CharField(default='', max_length=200)),
                ('addr2', models.CharField(default='', max_length=200)),
                ('oldAddr', models.CharField(default='', max_length=200)),
                ('organ', models.CharField(default='', max_length=50)),
                ('organManager', models.CharField(default='', max_length=10)),
                ('organPhone', models.CharField(default='', max_length=20)),
                ('organMail', models.CharField(default='', max_length=50)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 45, 341156))),
                ('insUs', models.CharField(null=True, max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 45, 341196))),
                ('modUs', models.CharField(null=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 45, 341834))),
                ('insUs', models.CharField(null=True, max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 45, 341873))),
                ('modUs', models.CharField(null=True, max_length=30)),
                ('festivalCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
