# Generated by Django 3.1.1 on 2020-09-30 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='addr1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='addr2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='descriptionDetail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='festival',
            name='descriptionHeader',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='festival',
            name='endDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='festival',
            name='festivalCd',
            field=models.CharField(default='0000', max_length=5),
        ),
        migrations.AddField(
            model_name='festival',
            name='innerMapUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 42, 20, 316718)),
        ),
        migrations.AddField(
            model_name='festival',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='festival',
            name='joinCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 42, 20, 316757)),
        ),
        migrations.AddField(
            model_name='festival',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='festival',
            name='oldAddr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='festival',
            name='organ',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='festival',
            name='organMail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='festival',
            name='organManger',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='festival',
            name='organPhone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='festival',
            name='simulOperCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='festival',
            name='startDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='festival',
            name='festivalName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
