# Generated by Django 3.1.2 on 2020-10-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20201022_1451'),
        ('festivals', '0002_auto_20201022_1445'),
    ]

    operations = [
    ]
