# Generated by Django 3.1.1 on 2020-09-30 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_auto_20200930_1645'),
        ('festivals', '0002_auto_20200930_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 45, 11, 34877)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 45, 11, 34915)),
        ),
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 45, 11, 35711))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 16, 45, 11, 35753))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('festivalCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
