# Generated by Django 3.1.4 on 2021-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_join_storecd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='openYn',
            field=models.CharField(default='Y', max_length=5),
        ),
    ]
