# Generated by Django 3.1.4 on 2021-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_auto_20210308_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='openYn',
            field=models.CharField(default='Y', max_length=17),
        ),
    ]
