# Generated by Django 3.1.3 on 2020-11-18 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_auto_20201117_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 399417)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 399462)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 400218)),
        ),
        migrations.AlterField(
            model_name='join',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 2, 26, 400266)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
    ]
