# Generated by Django 3.1.3 on 2020-11-20 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_auto_20201118_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='innerMapUrl',
        ),
        migrations.AddField(
            model_name='festival',
            name='img',
            field=models.ImageField(null=True, upload_to='images/festival/img'),
        ),
        migrations.AddField(
            model_name='festival',
            name='innerMap',
            field=models.ImageField(null=True, upload_to='images/festival/innerMap'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 14, 39, 752642)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 14, 39, 752691)),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 14, 39, 753678)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 2, 14, 39, 753719)),
        ),
    ]
