# Generated by Django 3.1.3 on 2020-11-22 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0016_auto_20201122_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='innerMap',
            field=models.ImageField(blank=True, null=True, upload_to='images/festival/innerMap'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 17, 17, 42, 61023), null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 17, 17, 42, 61057), null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 17, 17, 42, 61930)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 17, 17, 42, 62045)),
        ),
    ]
