# Generated by Django 3.1.2 on 2020-10-19 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0018_merge_20201015_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='descriptionHeader',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 36, 35, 534475)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 36, 35, 534523)),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 36, 35, 535328)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 36, 35, 535371)),
        ),
    ]
