# Generated by Django 3.1.4 on 2020-12-17 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0019_auto_20201212_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 17, 23, 27, 18, 968059), null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 17, 23, 27, 18, 968098), null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 23, 27, 18, 968997)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 23, 27, 18, 969035)),
        ),
    ]
