# Generated by Django 3.1.2 on 2020-10-19 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0019_auto_20201019_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='descriptionDetail',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 43, 0, 986051)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 43, 0, 986162)),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 43, 0, 987289)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 20, 43, 0, 987341)),
        ),
    ]
