# Generated by Django 3.1.2 on 2020-10-20 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0020_auto_20201019_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 381417)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 381461)),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 382196)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 382237)),
        ),
    ]
