# Generated by Django 3.1.2 on 2020-10-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_join_storecd'),
        ('festivals', '0021_auto_20201020_2025'),
    ]

    operations = [
    ]
