# Generated by Django 3.1.4 on 2020-12-18 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0023_auto_20201218_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 19, 28, 16, 748855), null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 19, 28, 16, 748903), null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 28, 16, 749790)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 28, 16, 749829)),
        ),
    ]
