# Generated by Django 3.1.4 on 2020-12-20 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0024_auto_20201218_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='openYn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='festival',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 20, 13, 46, 13, 550644), null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 20, 13, 46, 13, 550685), null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 46, 13, 551767)),
        ),
        migrations.AlterField(
            model_name='join',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 13, 46, 13, 551810)),
        ),
    ]
