# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0027_auto_20201225_1053'),
        ('festivals', '0028_auto_20201225_1401'),
    ]

    operations = [
    ]
