# Generated by Django 3.1.1 on 2020-09-29 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_auto_20200930_0122'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brandCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='imgSmallUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 22, 2, 218173)),
        ),
        migrations.AddField(
            model_name='item',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='itemCd',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='itemFg',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='kdsSendYn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 22, 2, 218210)),
        ),
        migrations.AddField(
            model_name='item',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='ordPrtText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='ordPrtYn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='setYn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='takeOutPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='useYn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
