# Generated by Django 3.1.1 on 2020-09-29 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_auto_20200930_0122'),
        ('items', '0002_auto_20200930_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brandCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 22, 48, 994980)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 22, 48, 995024)),
        ),
    ]
