# Generated by Django 3.1.4 on 2020-12-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201229_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemDesc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
