# Generated by Django 3.1.4 on 2021-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210118_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcat',
            name='useYn',
            field=models.CharField(default='Y', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemFg',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='kdsSendYn',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='ordPrtYn',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='setYn',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='useYn',
            field=models.CharField(default='Y', max_length=5),
        ),
    ]
