# Generated by Django 3.1.4 on 2020-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_itemdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemDesc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
