# Generated by Django 3.1.1 on 2020-09-29 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20200930_0142'),
        ('items', '0007_auto_20200930_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemAddCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addCatCd', models.CharField(default='00000', max_length=5)),
                ('addCatNm', models.CharField(default='', max_length=20)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 963443))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 963478))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 960464)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 960503)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 961202)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 961238)),
        ),
        migrations.CreateModel(
            name='ItemSetOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeItemCd', models.CharField(default='00000', max_length=20)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 961954))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 962015))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('subItemCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='itemAddCatMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 964148))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 964190))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('addCatCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.itemaddcat')),
                ('addItemCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemAddCd', models.CharField(default='00000', max_length=20)),
                ('itemSort', models.IntegerField(default=0)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 962755))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 1, 42, 18, 962791))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('itemCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
