# Generated by Django 3.1.1 on 2020-09-30 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200930_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 340926)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 340967)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 343494)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 343537)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 344298)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 344363)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 344945)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 344989)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 341898)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 341945)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 342731)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 55, 45, 342771)),
        ),
    ]
