# Generated by Django 3.1.1 on 2020-09-30 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200930_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 247784)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 247844)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 250540)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 250581)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 251682)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 251821)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 252963)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 253062)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 248807)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 248850)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 249750)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 59, 41, 249795)),
        ),
    ]
