# Generated by Django 3.1.1 on 2020-09-30 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20200930_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 26008)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 26054)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 28068)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 28104)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 28698)),
        ),
        migrations.AlterField(
            model_name='itemaddcat',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 28733)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 29226)),
        ),
        migrations.AlterField(
            model_name='itemaddcatmaster',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 29268)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 26812)),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 26849)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 27439)),
        ),
        migrations.AlterField(
            model_name='itemsetopt',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 4, 37, 27482)),
        ),
    ]
