# Generated by Django 3.1.1 on 2020-09-30 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_auto_20200930_1314'),
        ('items', '0011_auto_20200930_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 272085))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 272218))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AddCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addCatCd', models.CharField(default='00000', max_length=5)),
                ('addCatNm', models.CharField(default='', max_length=20)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 271246))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 271341))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('subItemCd', models.CharField(default='00000', max_length=20)),
                ('subItemQty', models.IntegerField(default=1)),
                ('subItemPric', models.FloatField(default=0.0)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 268442))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 268532))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SetOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeItemCd', models.CharField(default='00000', max_length=20)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 269586))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 269627))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemaddcatmaster',
            name='addCatCd',
        ),
        migrations.RemoveField(
            model_name='itemaddcatmaster',
            name='addItemCd',
        ),
        migrations.RemoveField(
            model_name='itemset',
            name='setItemCd',
        ),
        migrations.RemoveField(
            model_name='itemsetopt',
            name='storeCd',
        ),
        migrations.RemoveField(
            model_name='itemsetopt',
            name='subItemCd',
        ),
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 266821)),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 266862)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 270320)),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 14, 31, 270356)),
        ),
        migrations.DeleteModel(
            name='itemAddCat',
        ),
        migrations.DeleteModel(
            name='itemAddCatMaster',
        ),
        migrations.DeleteModel(
            name='ItemSet',
        ),
        migrations.DeleteModel(
            name='ItemSetOpt',
        ),
        migrations.AddField(
            model_name='setopt',
            name='subItemCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='set',
            name='setItemCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='add',
            name='addCatCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.addcat'),
        ),
        migrations.AddField(
            model_name='add',
            name='addItemCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
