# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_auto_20201225_1053'),
        ('items', '0033_auto_20201225_1401'),
    ]

    operations = [
    ]
