# Generated by Django 3.1.2 on 2020-10-05 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_auto_20201005_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 389419), null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 389507), null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcat',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 388443), null=True),
        ),
        migrations.AlterField(
            model_name='addcat',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcat',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 388502), null=True),
        ),
        migrations.AlterField(
            model_name='addcat',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 383834), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 383906), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 387672), null=True),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 387712), null=True),
        ),
        migrations.AlterField(
            model_name='itemadd',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 385270), null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 385345), null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setopt',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 386943), null=True),
        ),
        migrations.AlterField(
            model_name='setopt',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setopt',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 22, 37, 39, 386990), null=True),
        ),
        migrations.AlterField(
            model_name='setopt',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30, null=True),
        ),
    ]
