# Generated by Django 3.1.4 on 2021-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_saleheader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='receiptId',
            field=models.CharField(default='', max_length=30),
        ),
    ]
