# Generated by Django 3.1.4 on 2020-12-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_saleheader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='saleDay',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='saleTime',
            field=models.CharField(default='', max_length=6),
        ),
    ]
