# Generated by Django 3.1.4 on 2021-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_cardlog_receiptid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='confirmTime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
