# Generated by Django 3.1.4 on 2021-02-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_saleheader_confirmtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='cancelId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
