# Generated by Django 3.1.4 on 2021-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_cardlog_cancelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='callNo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
