# Generated by Django 3.1.4 on 2021-03-07 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_saleheader_callno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(default='00000', max_length=10)),
                ('saleDt', models.CharField(default='00000000', max_length=8)),
                ('posNo', models.CharField(default='91', max_length=5)),
                ('billNo', models.CharField(default='00000', max_length=10)),
                ('seq', models.IntegerField(default=1)),
                ('saleFlag', models.CharField(default='000', max_length=3)),
                ('etcAmt', models.FloatField(default=0.0)),
                ('etcPayCatCd', models.CharField(default='000', max_length=5)),
                ('etcPayCd', models.CharField(default='000', max_length=5)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modUs', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
