# Generated by Django 3.1.2 on 2020-11-03 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20201029_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleheader',
            old_name='cashAmt',
            new_name='kkmAmt',
        ),
        migrations.RenameField(
            model_name='saleheader',
            old_name='etcAmt',
            new_name='supAmt',
        ),
        migrations.RenameField(
            model_name='saleheader',
            old_name='supplyAmt',
            new_name='totDcAmt',
        ),
        migrations.RenameField(
            model_name='saleheader',
            old_name='totalQty',
            new_name='totQty',
        ),
        migrations.RenameField(
            model_name='saleheader',
            old_name='totalDcAmt',
            new_name='totSaleAmt',
        ),
        migrations.RemoveField(
            model_name='saleheader',
            name='mealCd',
        ),
        migrations.RemoveField(
            model_name='saleheader',
            name='mealName',
        ),
        migrations.RemoveField(
            model_name='saleheader',
            name='totalSaleAmt',
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 537544), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 537577), null=True),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 536636), null=True),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 536676), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 540911), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 540947), null=True),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 538444), null=True),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 538483), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 539855), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 539892), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 535730), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 535768), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 540383), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 540416), null=True),
        ),
        migrations.AlterField(
            model_name='standardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 539157), null=True),
        ),
        migrations.AlterField(
            model_name='standardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 10, 22, 539196), null=True),
        ),
    ]
