# Generated by Django 3.1.4 on 2021-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_etclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='etcAmt',
            field=models.FloatField(default=0.0),
        ),
    ]
