# Generated by Django 3.1.2 on 2020-11-03 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20201103_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardlog',
            old_name='approvalDate',
            new_name='apprDate',
        ),
        migrations.RenameField(
            model_name='cardlog',
            old_name='approvalFlag',
            new_name='apprFlag',
        ),
        migrations.RenameField(
            model_name='cardlog',
            old_name='approvalNo',
            new_name='apprNo',
        ),
        migrations.RenameField(
            model_name='cardlog',
            old_name='approvalTime',
            new_name='apprTime',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='supplyAmt',
            new_name='supAmt',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='totalDcAmt',
            new_name='totDcAmt',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='totalSaleAmt',
            new_name='totSaleAmt',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgApprovalNo',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgBillNo',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgPosNo',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgSaleDate',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgSeq',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='orgStoreCd',
        ),
        migrations.RemoveField(
            model_name='cardlog',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='etclog',
            name='orgBillNo',
        ),
        migrations.RemoveField(
            model_name='etclog',
            name='orgPosNo',
        ),
        migrations.RemoveField(
            model_name='etclog',
            name='orgSaleDate',
        ),
        migrations.RemoveField(
            model_name='etclog',
            name='orgSeq',
        ),
        migrations.RemoveField(
            model_name='etclog',
            name='orgStoreCd',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='mealCd',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='mealName',
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 416048), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 416083), null=True),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 415185), null=True),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 415220), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 420329), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 420364), null=True),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 417287), null=True),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 417326), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 419156), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 419194), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 414189), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 414230), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 419776), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 419819), null=True),
        ),
        migrations.AlterField(
            model_name='standardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 418237), null=True),
        ),
        migrations.AlterField(
            model_name='standardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 40, 14, 418274), null=True),
        ),
    ]
