# Generated by Django 3.1.4 on 2021-03-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_etclog_sendyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etclog',
            name='sendYn',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
