# Generated by Django 3.1.4 on 2021-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20210308_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='apprFlag',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='instFlag',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='instMonth',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='orgPosNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='posNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='stateFlag',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='posNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='etcPayCatCd',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='etcPayCd',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='etclog',
            name='posNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='orderUnit',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='posNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='orderStatus',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='orgPosNo',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='posNo',
            field=models.CharField(default='91', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='saleDay',
            field=models.CharField(default='', max_length=3),
        ),
    ]
