# Generated by Django 3.1.2 on 2020-11-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_auto_20201105_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='apprDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='apprNo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='apprTime',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='billNo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='cardCd',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='cardNo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 70733), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 70770), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='orgApprNo',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='orgBillNo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='orgSaleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='orgStoreCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='saleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='saleFlag',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='vanCd',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='groupCd',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 72616), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='keymapCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 72649), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='saleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='approvalFlag',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='cdmtCd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 71511), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 71550), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='orderUnit',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='purchaseDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='purchaseFlag',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='registerNo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='billNo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 69509), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='itemCd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='itemSellGroup',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='itemSellLevel',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='itemSellType',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 69545), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='orderType',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='saleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='saleFlag',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='billNo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='saleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='saleFlag',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 72044), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='itemCd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 16, 9, 11, 72082), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='saleDt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='storeCd',
            field=models.CharField(default='', max_length=10),
        ),
    ]
