# Generated by Django 3.1.3 on 2020-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0019_auto_20201117_1438'),
        ('trades', '0018_auto_20201117_1516'),
    ]

    operations = [
    ]
