# Generated by Django 3.1.3 on 2020-11-21 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0027_auto_20201121_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleheader',
            name='completeTime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 170657), null=True),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 170697), null=True),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='saleheader',
            name='pickupTime',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 172837), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 172870), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 174718), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 174752), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 173649), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 173689), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 171851), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 171884), null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 174190), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 53, 50, 174223), null=True),
        ),
    ]
