# Generated by Django 3.1.4 on 2020-12-24 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0037_auto_20201223_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeId', models.CharField(default='', max_length=10)),
                ('saleDt', models.CharField(default='', max_length=8)),
                ('posNo', models.CharField(default='91', max_length=5)),
                ('billNo', models.CharField(default='', max_length=10)),
                ('userId', models.CharField(default='', max_length=10)),
                ('itemId', models.CharField(default='', max_length=10)),
                ('tradeErrorCode', models.CharField(blank=True, max_length=3)),
                ('tradeErrorMsg', models.CharField(default='', max_length=100)),
                ('context', models.CharField(default='', max_length=255)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 465608), null=True)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 465642), null=True)),
                ('modUs', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 462731), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 462767), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 465004), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 465039), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 463732), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 463770), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 461585), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 461625), null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 460328), null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 460369), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 464427), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 22, 27, 39, 464464), null=True),
        ),
    ]
