# Generated by Django 3.1.4 on 2020-12-24 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0039_auto_20201224_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='exception',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 382635), null=True),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 382673), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 384761), null=True),
        ),
        migrations.AlterField(
            model_name='cornerstatelog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 384797), null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 385454), null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 385493), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 383576), null=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 383621), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 381567), null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 381606), null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 380352), null=True),
        ),
        migrations.AlterField(
            model_name='saleheader',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 380397), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 384197), null=True),
        ),
        migrations.AlterField(
            model_name='soldoutlog',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 35, 3, 384235), null=True),
        ),
    ]
