# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0042_auto_20201225_1401'),
        ('trades', '0038_auto_20201225_1053'),
    ]

    operations = [
    ]
