# Generated by Django 3.1.2 on 2020-10-21 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandCd', models.CharField(default='00000', max_length=5)),
                ('brandName', models.CharField(default='', max_length=100)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 22, 59, 24, 240682))),
                ('insUs', models.CharField(null=True, max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 22, 59, 24, 240735))),
                ('modUs', models.CharField(null=True, max_length=30)),
            ],
        ),
    ]
