# Generated by Django 3.1.1 on 2020-09-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brandName',
        ),
    ]
