# Generated by Django 3.1.1 on 2020-09-29 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_remove_brand_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brandCd',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='brand',
            name='brandName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 23, 47, 54, 162421)),
        ),
        migrations.AddField(
            model_name='brand',
            name='insUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='brand',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 23, 47, 54, 162463)),
        ),
        migrations.AddField(
            model_name='brand',
            name='modUs',
            field=models.CharField(default='defaultValue', max_length=30),
        ),
        migrations.AddField(
            model_name='brand',
            name='useYn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
