# Generated by Django 3.1.4 on 2021-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20210308_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandCd',
            field=models.CharField(default='00000', max_length=1),
        ),
        migrations.AlterField(
            model_name='brand',
            name='useYn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
