# Generated by Django 3.1.3 on 2020-11-18 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_auto_20201118_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 359318)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 359395)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
