# Generated by Django 3.1.4 on 2020-12-12 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0015_auto_20201123_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 17, 27, 33, 819284)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 17, 27, 33, 819306)),
        ),
    ]
