# Generated by Django 3.1.2 on 2020-10-12 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0041_auto_20201004_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 44, 23, 894941)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 44, 23, 894978)),
        ),
    ]
