# Generated by Django 3.1.2 on 2020-10-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0043_auto_20201015_1422'),
        ('brands', '0043_auto_20201015_1402'),
    ]

    operations = [
    ]
