# Generated by Django 3.1.2 on 2020-10-20 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0044_merge_20201015_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 389646)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 25, 12, 389726)),
        ),
    ]
