# Generated by Django 3.1.4 on 2020-12-28 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDt', models.CharField(max_length=8, null=True)),
                ('billNo', models.CharField(max_length=10, null=True)),
                ('seq', models.IntegerField(default=1)),
                ('context', models.TextField(null=True)),
                ('deleteYn', models.CharField(default='N', max_length=1)),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modUs', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDt', models.CharField(blank=True, max_length=8, null=True)),
                ('billNo', models.CharField(blank=True, max_length=10, null=True)),
                ('reviewDt', models.CharField(blank=True, max_length=8, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/review')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/review')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/review')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images/review')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='images/review')),
                ('deleteYn', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('insDt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('insUs', models.CharField(blank=True, max_length=30, null=True)),
                ('modDt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modUs', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('insUs', models.CharField(max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modUs', models.CharField(max_length=30, null=True)),
                ('review', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
