# Generated by Django 3.1.4 on 2021-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210118_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='deleteYn',
            field=models.CharField(default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='likeYn',
            field=models.CharField(default='Y', max_length=5),
        ),
    ]
