# Generated by Django 3.1.2 on 2020-10-27 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20201027_2358'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20201027_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 807678)),
        ),
        migrations.AlterField(
            model_name='review',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 807720)),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 809053)),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 809088)),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDt', models.CharField(max_length=8, null=True)),
                ('billNo', models.CharField(max_length=10, null=True)),
                ('seq', models.IntegerField(default=1)),
                ('context', models.TextField(null=True)),
                ('deleteYn', models.CharField(default='N', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 809695))),
                ('insUs', models.CharField( max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 58, 45, 809729))),
                ('modUs', models.CharField( max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
