# Generated by Django 3.1.3 on 2020-11-18 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20201118_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 368463)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 368708)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 363666)),
        ),
        migrations.AlterField(
            model_name='review',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 363738)),
        ),
        migrations.AlterField(
            model_name='review',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 366132)),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 366201)),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 364914)),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='insUs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 23, 5, 3, 364986)),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='modUs',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
