# Generated by Django 3.1.3 on 2020-11-22 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_auto_20201122_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0016_auto_20201121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 19, 26, 5, 22959)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 19, 26, 5, 23001)),
        ),
        migrations.AlterField(
            model_name='review',
            name='billNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='deleteYn',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='images/review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='images/review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 19, 26, 5, 20860), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='insUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 19, 26, 5, 20909), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modUs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='saleDt',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='storeCd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 19, 26, 5, 22227)),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 19, 26, 5, 22266)),
        ),
    ]
