# Generated by Django 3.1.4 on 2020-12-18 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20201217_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 9, 25, 737958)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 9, 25, 737996)),
        ),
        migrations.AlterField(
            model_name='review',
            name='insDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 19, 9, 25, 735928), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modDt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 19, 9, 25, 735967), null=True),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 9, 25, 737144)),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 9, 25, 737184)),
        ),
    ]
