# Generated by Django 3.1.2 on 2020-10-21 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posPage', models.IntegerField(default=0)),
                ('posIndex', models.IntegerField(default=0)),
                ('soldoutYn', models.CharField(max_length=1, null=True)),
                ('cprtGroupCd', models.CharField(max_length=5, null=True)),
                ('dispYn', models.CharField(default='Y', max_length=1)),
                ('expectCnt', models.IntegerField(default=0)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 383250))),
                ('insUs', models.CharField(null=True, max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 383309))),
                ('modUs', models.CharField( max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoreKeymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keymapCd', models.CharField(default='000', max_length=10)),
                ('keymapName', models.CharField(default='', max_length=30)),
                ('blankImgUrl', models.CharField(max_length=200, null=True)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 380586))),
                ('insUs', models.CharField( max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 380620))),
                ('modUs', models.CharField( max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TouchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchGroupCd', models.CharField(default='000', max_length=5)),
                ('touchGroupName', models.CharField(default='', max_length=100)),
                ('imgUrl', models.CharField(max_length=200, null=True)),
                ('imgUseYn', models.CharField(default='N', max_length=1)),
                ('posPage', models.IntegerField(default=0)),
                ('posIndex', models.IntegerField(default=0)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 382412))),
                ('insUs', models.CharField( max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 23, 0, 19, 382451))),
                ('modUs', models.CharField( max_length=30)),
                ('keymapCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.storekeymap')),
            ],
        ),
    ]
