# Generated by Django 3.1.1 on 2020-09-30 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0024_auto_20200930_1944'),
        ('stores', '0031_auto_20200930_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posPage', models.IntegerField(default=0)),
                ('posIndex', models.IntegerField(default=0)),
                ('soldOutYn', models.CharField(default='N', max_length=1)),
                ('cprtGroupCd', models.CharField(default='000', max_length=5)),
                ('dispYn', models.CharField(default='Y', max_length=1)),
                ('expectCnt', models.IntegerField(default=0)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 547995))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 548030))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('itemCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='TouchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupCd', models.CharField(default='000', max_length=5)),
                ('groupName', models.CharField(default='', max_length=100)),
                ('imgUrl', models.CharField(blank=True, max_length=200)),
                ('imgUseYn', models.CharField(default='N', max_length=1)),
                ('posPage', models.IntegerField(default=0)),
                ('posIndex', models.IntegerField(default=0)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 547154))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 547190))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('keymapCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.keymap')),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreKeymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keymapCd', models.CharField(default='000', max_length=10)),
                ('keymapName', models.CharField(default='', max_length=30)),
                ('blankImgUrl', models.CharField(blank=True, max_length=200)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 545243))),
                ('insUs', models.CharField(default='defaultValue', max_length=30)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 19, 44, 48, 545282))),
                ('modUs', models.CharField(default='defaultValue', max_length=30)),
                ('storeCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='keymap',
            name='keymapCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.storekeymap'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='storeCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='touchGroupCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.touchgroup'),
        ),
    ]
