# Generated by Django 3.1.4 on 2020-12-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20201229_0343'),
        ('stores', '0001_initial'),
        ('keymaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchgroup',
            name='storeCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='storekeymap',
            name='storeCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='itemCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='keymapCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.storekeymap'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='storeCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='keymap',
            name='touchGroupCd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keymaps.touchgroup'),
        ),
    ]
