# Generated by Django 3.1.4 on 2021-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymaps', '0005_auto_20210308_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='cprtGroupCd',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='touchGroupCd',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
