# Generated by Django 3.1.2 on 2020-10-04 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymaps', '0009_auto_20201004_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 982351)),
        ),
        migrations.AlterField(
            model_name='keymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 982388)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='blankImgUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 979856)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 979896)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='imgUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 981493)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 3, 41, 981527)),
        ),
    ]
