# Generated by Django 3.1.2 on 2020-10-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymaps', '0013_auto_20201005_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touchgroup',
            old_name='groupCd',
            new_name='touchGroupCd',
        ),
        migrations.RenameField(
            model_name='touchgroup',
            old_name='groupName',
            new_name='touchGroupName',
        ),
        migrations.AlterField(
            model_name='keymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 956548)),
        ),
        migrations.AlterField(
            model_name='keymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 956582)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 953841)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 953876)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 955670)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 4, 32, 955711)),
        ),
    ]
