# Generated by Django 3.1.2 on 2020-10-07 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymaps', '0015_auto_20201007_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='cprtGroupCd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='keymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 328381)),
        ),
        migrations.AlterField(
            model_name='keymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 328421)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 325381)),
        ),
        migrations.AlterField(
            model_name='storekeymap',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 325420)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 327399)),
        ),
        migrations.AlterField(
            model_name='touchgroup',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 9, 52, 327447)),
        ),
    ]
