# Generated by Django 3.1.2 on 2020-10-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keymaps', '0002_auto_20201021_1724'),
        ('keymaps', '0020_auto_20201020_2025'),
    ]

    operations = [
    ]
