# Generated by Django 3.1.2 on 2020-10-24 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cprts', '0005_auto_20201024_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(max_length=10, null=True)),
                ('refreshTime', models.IntegerField(default=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 19, 51, 13, 647188), null=True)),
                ('insUs', models.CharField( max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 19, 51, 13, 647241), null=True)),
                ('modUs', models.CharField( max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(max_length=10, null=True)),
                ('monitorFlag', models.CharField(default=1, max_length=1)),
                ('summaryYn', models.CharField(default='Y', max_length=1)),
                ('fontSize', models.CharField(default=10, max_length=1)),
                ('orderExpandYn', models.CharField(default='Y', max_length=1)),
                ('soundYn', models.CharField(default='Y', max_length=1)),
                ('backRgb', models.CharField(max_length=20, null=True)),
                ('foreRgb', models.CharField(max_length=20, null=True)),
                ('revertRgb', models.CharField(max_length=20, null=True)),
                ('voidRgb', models.CharField(max_length=20, null=True)),
                ('eatInRgb', models.CharField(max_length=20, null=True)),
                ('takeOutRgb', models.CharField(max_length=20, null=True)),
                ('deliveryRgb', models.CharField(max_length=20, null=True)),
                ('driveThruRgb', models.CharField(max_length=20, null=True)),
                ('preOrderRgb', models.CharField(max_length=20, null=True)),
                ('useYn', models.CharField(default='Y', max_length=1)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 19, 51, 13, 648145), null=True)),
                ('insUs', models.CharField( max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 19, 51, 13, 648184), null=True)),
                ('modUs', models.CharField( max_length=30, null=True)),
                ('cprtGroupCd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cprts.group')),
            ],
        ),
    ]
