# Generated by Django 3.1.4 on 2021-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdsheader',
            name='orderStatus',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='fontSize',
            field=models.CharField(default=10, max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='monitorFlag',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='orderExpandYn',
            field=models.CharField(default='Y', max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='soundYn',
            field=models.CharField(default='Y', max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='summaryYn',
            field=models.CharField(default='Y', max_length=5),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='useYn',
            field=models.CharField(default='Y', max_length=5),
        ),
    ]
