# Generated by Django 3.1.4 on 2021-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdses', '0004_auto_20210308_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdsdetail',
            name='posNo',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='kdsheader',
            name='orderStatus',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='kdsheader',
            name='posNo',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='fontSize',
            field=models.CharField(default=10, max_length=3),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='monitorFlag',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
