# Generated by Django 3.1.3 on 2020-11-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdses', '0005_auto_20201105_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='KdsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(max_length=10, null=True)),
                ('saleDt', models.CharField(blank=True, max_length=8)),
                ('posNo', models.CharField(blank=True, max_length=5)),
                ('billNo', models.CharField(blank=True, max_length=10)),
                ('seq', models.IntegerField(default=1)),
                ('itemName', models.CharField(blank=True, max_length=20)),
                ('qty', models.IntegerField(default=1)),
                ('itemSellGroup', models.CharField(blank=True, max_length=3)),
                ('itemSellLevel', models.CharField(blank=True, max_length=3)),
                ('itemSellType', models.CharField(blank=True, max_length=3)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 909192), null=True)),
                ('insUs', models.CharField( max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 909226), null=True)),
                ('modUs', models.CharField( max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KdsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeCd', models.CharField(max_length=10, null=True)),
                ('saleDt', models.CharField(blank=True, max_length=8)),
                ('posNo', models.CharField(blank=True, max_length=5)),
                ('billNo', models.CharField(blank=True, max_length=10)),
                ('orderStatus', models.CharField(blank=True, max_length=1)),
                ('saleTime', models.CharField(blank=True, max_length=8)),
                ('insDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 908602), null=True)),
                ('insUs', models.CharField( max_length=30, null=True)),
                ('modDt', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 908640), null=True)),
                ('modUs', models.CharField( max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='master',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 907061), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 907103), null=True),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 907804), null=True),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 23, 16, 12, 907844), null=True),
        ),
    ]
