# Generated by Django 3.1.4 on 2020-12-18 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdses', '0017_auto_20201218_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdsdetail',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 130649), null=True),
        ),
        migrations.AlterField(
            model_name='kdsdetail',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 130696), null=True),
        ),
        migrations.AlterField(
            model_name='kdsheader',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 130003), null=True),
        ),
        migrations.AlterField(
            model_name='kdsheader',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 130037), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 128441), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 128488), null=True),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='insDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 129251), null=True),
        ),
        migrations.AlterField(
            model_name='setmaster',
            name='modDt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 19, 24, 59, 129285), null=True),
        ),
    ]
