# Generated by Django 3.1.4 on 2020-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdses', '0022_auto_20201225_1401'),
        ('kdses', '0021_auto_20201225_1053'),
    ]

    operations = [
    ]
